### ISSUE TITLE
Deploy Airnode contracts on Sepolia

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#1039]
Documentation for https://github.com/api3dao/airnode/issues/1452

**Comment by dcroote** [comment]
The addresses should appear within [the contract addresses page](https://docs.api3.org/airnode/v0.8/reference/airnode-addresses.html) automatically because the table is populated by a Vue component that pulls from `airnode-protocol/deployments/references.json`:

https://github.com/api3dao/api3-docs/blob/7ad8646eecf19b6ba5f8b337949aec3969069a5e/docs/.vuepress/components/airnode/ContractAddresses.vue#L77-L79
