### ISSUE TITLE
Tutorials Per API Partner

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#154]
This suggestion cae from the forum.

_user: telecomsxchange
I think it would be useful to partners to have a tutorial section in the API3 developer docs where each partner can write up a tutorial on a use case of their choice. This would be great for API3 SEO ranking and for Partners to easily link developers to that article for quick start._

See [Tutorials Per API Partner](https://forum.api3.org/t/tutorials-per-api-partner/431/3) from the API3 forum.

**Comment by wkande** [comment]
The problem with this concept (regardless where it lives) is API provider upkeep. Once these tutorials are created will they get maintained, retired? In the "real world" this needs to be done in an environment with a TTL clause. If the API provider does not update their info on a regular basis then the tutorial will become inactive. This would require more than a static website or  a bunch of GitHub repos.

**Comment by wkande** [comment]
This might be possible with an advanced component. The docs would now need and authentication method to protect each use case.

I have not heard any further conversations on the issue since Aug 10th and not sure who had came up with the idea. Keeping this issue alive for now hoping for other input.

**Comment by dcroote** [comment]
I think this is at least partially covered by the [Web3 API catalog on api3.org](https://api3.org/apis). For instance, the [page for API provider Interzoid](https://api3.org/apis/Interzoid/Interzoid%20APIs) links to Airnode instructions and parameters for calling various endpoints.

**Comment by 37Rb** [comment]
I agree with @dcroote. Rather than doing this in our official docs it should be done in the API-provider-owned Airnode docs for each API, which are linked to with the "+ Airnode" link on the [API pages on our site](https://api3.org/apis/Interzoid/Interzoid%20APIs). I think the marketing team should provide these examples. We did [something similar with Bitcoin Bankathon here](https://github.com/api3m/bitcoin-bankathon-airnode-client#open-bank-project--get-banks). We can work with the account managers to get good examples into the API Airnode docs.

**Comment by wkande** [comment]
Then we have a good consensus. I am closing this issue related to the Docs supporting this idea. I
