### ISSUE TITLE
Revise pre-alpha designated wallet docs

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#161]
"Sponsor wallets" are referred to here: https://docs.api3.org/pre-alpha/protocols/request-response/designated-wallet.html#the-custodial-nature-of-the-designated-wallets
That is v0.1.0 terminology and shouldn't be used for pre-alpha

Also, let's revise the wording of the entire bit around this argument
https://api3workspace.slack.com/archives/G01F4ACTA03/p1629210559019100?thread_ts=1629199603.008800&cid=G01F4ACTA03
while avoiding the word "custodial" altogether as it has multiple interpretations (possession vs. obligation)

**Comment by wkande** [comment]
Caught that pre-alpha error myself. I have now created two components, one for /pre-alpha designated wallets and one for /next sponsor wallets. I am adding Erich's text into these components since it appears in the docs more than once. Earlier you wanted the warning to be in more than one place. Now if Erich wants to change the text again it can be done in one place.

Closing this ticket since it is related to Erich's PR #162. I will not merge the PR since it does not include the new components but did move Erich's text into the components.
