### ISSUE TITLE
Branch Deployment caching pages

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#552]
While both the production deployment and branch deployments have the same meta tags in index.html, the branch deployments are not reflecting the updated pages when the reader visits them after a second deployment of the seat to Firebase.

Not sure if the two hosting services (GH-pages and Firebase) use the same caching strategy. The following are not present that I can see on either. 

<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">

**Comment by dcroote** [comment]
I was able to reproduce the update not appearing upon second deployment, but it actually looks like the _**browser**_ is caching the site because I was able to hard refresh the page (Ctrl + Shift + R on Windows Chrome) and the update appeared.

@wkande can you try this out next time you push multiple deployments in a branch? Instructions for [various operating systems and browsers are here](https://www.howtogeek.com/672607/how-to-hard-refresh-your-web-browser-to-bypass-your-cache/).

**Comment by wkande** [comment]
Same here. A simple browser refresh will force a reload to the newer version. So yes the browser is caching the pages. Problem is readers are not going to remember to do this.

I don't suppose there is any settings on Firebase to disable caching server side. I would guess not.

```
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
```
We could try this in the index.html file for the SPA but I am not sure the browser will always care. I will look into it.

**Comment by wkande** [comment]
Now that I think about it the approach above is probably useless as the docs are an SPA.
