### ISSUE TITLE
Links for sections don't work

### ISSUE THREAD

**Issue by An-dz** [api3dao/old-api3-docs#76]
In many places, like the OIS specification, there are lists of links to different parameters. Those links do not work, reason being that the ID generated for the anchors on the page requires an underline and they're case-sensitive.

In other words, the link points to `#1-oisFormat` but the ID of the anchor is `#_1-oisformat`.

**Comment by wkande** [comment]
Thanks again. I recall fixing a bunch of those but certainly did not get them all it appears.

**Comment by wkande** [comment]
Old anchors from GitBook are lingering. VuePress has different behavior.

**Anchors as related to header element in Markdown**
- Spaces must be replaced with a dash.
- When starting with 0-9, must be proceeded with an underscore.
- Periods replaced with a dash.
- A period/space combination replaced with a single dash.
- Asterisks are ignored so omit them.
- Use lowercase.
- Anchors must be proceeded with the file name (myfile.md#anchor) using the markdown extension otherwise go back on the browser history will not work.

**Comment by wkande** [comment]
Changed links in /pre-alpha and /next. See issue #85 about the need to get a more robust link checking Git Action.
